// Daftar negara + kode teleponnya, ditulis manual di frontend (statis).
//
// KENAPA STATIS (bukan dari API luar)?
// API restcountries.com yang tadinya dipakai sekarang mewajibkan API key
// buat versi terbarunya (v5) — dan API key itu TIDAK aman ditaro di kode
// frontend (semua orang bisa lihat lewat DevTools browser). Solusi yang
// benar: nanti kalau backend Node.js lo udah jalan, BACKEND yang nyimpen
// API key itu dengan aman dan yang manggil API luar, lalu frontend cukup
// minta datanya ke backend sendiri. Untuk sekarang, daftar manual ini cukup.
export const COUNTRY_CODES = [
  { name: 'Indonesia', dialCode: '+62', flag: '🇮🇩' },
  { name: 'United States', dialCode: '+1', flag: '🇺🇸' },
  { name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧' },
  { name: 'India', dialCode: '+91', flag: '🇮🇳' },
  { name: 'China', dialCode: '+86', flag: '🇨🇳' },
  { name: 'Japan', dialCode: '+81', flag: '🇯🇵' },
  { name: 'South Korea', dialCode: '+82', flag: '🇰🇷' },
  { name: 'Singapore', dialCode: '+65', flag: '🇸🇬' },
  { name: 'Malaysia', dialCode: '+60', flag: '🇲🇾' },
  { name: 'Thailand', dialCode: '+66', flag: '🇹🇭' },
  { name: 'Vietnam', dialCode: '+84', flag: '🇻🇳' },
  { name: 'Philippines', dialCode: '+63', flag: '🇵🇭' },
  { name: 'Brunei', dialCode: '+673', flag: '🇧🇳' },
  { name: 'Cambodia', dialCode: '+855', flag: '🇰🇭' },
  { name: 'Laos', dialCode: '+856', flag: '🇱🇦' },
  { name: 'Myanmar', dialCode: '+95', flag: '🇲🇲' },
  { name: 'Taiwan', dialCode: '+886', flag: '🇹🇼' },
  { name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰' },
  { name: 'Macau', dialCode: '+853', flag: '🇲🇴' },
  { name: 'Australia', dialCode: '+61', flag: '🇦🇺' },
  { name: 'New Zealand', dialCode: '+64', flag: '🇳🇿' },
  { name: 'Canada', dialCode: '+1', flag: '🇨🇦' },
  { name: 'Mexico', dialCode: '+52', flag: '🇲🇽' },
  { name: 'Brazil', dialCode: '+55', flag: '🇧🇷' },
  { name: 'Argentina', dialCode: '+54', flag: '🇦🇷' },
  { name: 'Chile', dialCode: '+56', flag: '🇨🇱' },
  { name: 'Colombia', dialCode: '+57', flag: '🇨🇴' },
  { name: 'Peru', dialCode: '+51', flag: '🇵🇪' },
  { name: 'Venezuela', dialCode: '+58', flag: '🇻🇪' },
  { name: 'Ecuador', dialCode: '+593', flag: '🇪🇨' },
  { name: 'Uruguay', dialCode: '+598', flag: '🇺🇾' },
  { name: 'Paraguay', dialCode: '+595', flag: '🇵🇾' },
  { name: 'Bolivia', dialCode: '+591', flag: '🇧🇴' },
  { name: 'Germany', dialCode: '+49', flag: '🇩🇪' },
  { name: 'France', dialCode: '+33', flag: '🇫🇷' },
  { name: 'Italy', dialCode: '+39', flag: '🇮🇹' },
  { name: 'Spain', dialCode: '+34', flag: '🇪🇸' },
  { name: 'Portugal', dialCode: '+351', flag: '🇵🇹' },
  { name: 'Netherlands', dialCode: '+31', flag: '🇳🇱' },
  { name: 'Belgium', dialCode: '+32', flag: '🇧🇪' },
  { name: 'Switzerland', dialCode: '+41', flag: '🇨🇭' },
  { name: 'Austria', dialCode: '+43', flag: '🇦🇹' },
  { name: 'Sweden', dialCode: '+46', flag: '🇸🇪' },
  { name: 'Norway', dialCode: '+47', flag: '🇳🇴' },
  { name: 'Denmark', dialCode: '+45', flag: '🇩🇰' },
  { name: 'Finland', dialCode: '+358', flag: '🇫🇮' },
  { name: 'Iceland', dialCode: '+354', flag: '🇮🇸' },
  { name: 'Poland', dialCode: '+48', flag: '🇵🇱' },
  { name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿' },
  { name: 'Slovakia', dialCode: '+421', flag: '🇸🇰' },
  { name: 'Hungary', dialCode: '+36', flag: '🇭🇺' },
  { name: 'Romania', dialCode: '+40', flag: '🇷🇴' },
  { name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬' },
  { name: 'Greece', dialCode: '+30', flag: '🇬🇷' },
  { name: 'Croatia', dialCode: '+385', flag: '🇭🇷' },
  { name: 'Serbia', dialCode: '+381', flag: '🇷🇸' },
  { name: 'Ireland', dialCode: '+353', flag: '🇮🇪' },
  { name: 'Russia', dialCode: '+7', flag: '🇷🇺' },
  { name: 'Ukraine', dialCode: '+380', flag: '🇺🇦' },
  { name: 'Turkey', dialCode: '+90', flag: '🇹🇷' },
  { name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦' },
  { name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪' },
  { name: 'Qatar', dialCode: '+974', flag: '🇶🇦' },
  { name: 'Kuwait', dialCode: '+965', flag: '🇰🇼' },
  { name: 'Bahrain', dialCode: '+973', flag: '🇧🇭' },
  { name: 'Oman', dialCode: '+968', flag: '🇴🇲' },
  { name: 'Jordan', dialCode: '+962', flag: '🇯🇴' },
  { name: 'Israel', dialCode: '+972', flag: '🇮🇱' },
  { name: 'Iraq', dialCode: '+964', flag: '🇮🇶' },
  { name: 'Iran', dialCode: '+98', flag: '🇮🇷' },
  { name: 'Egypt', dialCode: '+20', flag: '🇪🇬' },
  { name: 'South Africa', dialCode: '+27', flag: '🇿🇦' },
  { name: 'Nigeria', dialCode: '+234', flag: '🇳🇬' },
  { name: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
  { name: 'Ghana', dialCode: '+233', flag: '🇬🇭' },
  { name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹' },
  { name: 'Morocco', dialCode: '+212', flag: '🇲🇦' },
  { name: 'Algeria', dialCode: '+213', flag: '🇩🇿' },
  { name: 'Tunisia', dialCode: '+216', flag: '🇹🇳' },
  { name: 'Pakistan', dialCode: '+92', flag: '🇵🇰' },
  { name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩' },
  { name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰' },
  { name: 'Nepal', dialCode: '+977', flag: '🇳🇵' },
  { name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫' },
]